#ifndef _INCLUDE_PASSWORD_TYPE_H__
#define _INCLUDE_PASSWORD_TYPE_H__

#define PASSWORD_SU			100
#define PASSWORD_EYECARE	200 

#define DEFAULT_PASSWORD	TEXT("123")

#endif  // _INCLUDE_PASSWORD_TYPE_H__