//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MainUI.rc
//
#define IDR_RT_MANIFEST                 1
#define IDC_CLEAR                       2
#define IDOK2                           2
#define IDC_SEARCH_CLEAR                3
#define IDM_ABOUTBOX                    0x0010
#define IDS_ABOUTBOX                    101
#define IDC_TRAY_MENU                   101
#define IDC_STA_PASSWORD                101
#define IDC_STA_FUNCTION                101
#define IDC_STA_STATE                   101
#define IDD_MAINUI_DIALOG               102
#define IDS_TREE_LEV1_RULES             102
#define IDS_COMMENT_DNS                 103
#define IDS_COMMENT_IMAGE               104
#define IDS_COMMENT_TEXT                105
#define IDS_TREE_OPTIONS                106
#define IDS_TREE_EYECARE                107
#define IDS_TRAYMENU_SHOWUI             108
#define IDS_TRAYMENU_HIDEUI             109
#define IDR_HTML_DLGWHITEDNSLIST        110
#define IDS_TREE_TOOLSETTING            110
#define IDR_HTML_DLGCHANGEPASSWORD      111
#define IDS_TREE_LEV1_TOOLS             111
#define IDS_TREE_SCREEN_SAVE            112
#define IDS_TREE_WEB_HISTORY            113
#define IDS_DLG_WEBSITES_NAME           113
#define IDS_WEB_HISTORY_CLEAR           114
#define IDS_WEB_HISTORY_VIEW_HISTORY    115
#define IDS_WEB_HISTORY_EXPORT_WEBSITE_LIST 116
#define IDS_WEB_HISTORY_FILEDLG_DEFAULT 117
#define IDS_WEB_HISTORY_FILEDLG_EXT     118
#define IDS_ERROR_WEB_SET_FAILED        119
#define IDS_SCREEN_RECORD_CLEAR_BUTTON  120
#define IDS_CHECK_PASSWORD_WRONG        121
#define IDS_APP_SERVER_INIT_FAILED      122
#define IDS_EYECARE_STATE_EYECARE       123
#define IDS_EYECARE_STATE_ENTERTAIN     124
#define IDS_HOTKEY_CONFLICT             125
#define IDS_WEB_HISTORY_CLEAR_SUCC      126
#define IDS_DLG_SEACHWORD               127
#define IDR_MAINFRAME                   128
#define IDS_DLG_SEACHWORD_LAST_TIME     128
#define IDD_DLG_HELP                    129
#define IDS_DLG_SEACHWORD_SEARCH_ENGINE 129
#define IDD_DLG_ABOUT                   130
#define IDS_DLG_SEACHWORD_SEARCH_TIMES  130
#define IDS_DLG_WEBSITES                131
#define IDD_DLG_IMAGERULES              132
#define IDS_DLG_WEBSITE_VISIT_TIMES     132
#define IDD_DLG_ONLINE_RULE             133
#define IDS_DLG_WEBSITE_VISIT_LATEST_TIME 133
#define IDD_DLG_DNS_RULE                134
#define IDD_DLG_DNS_BLACKLIST           134
#define IDS_PROGRAM_CONTROL             134
#define IDD_DLG_SEARCH_RULE             135
#define IDS_DLG_PROGRAM_CONTROL_NAME    135
#define IDD_DLG_CONTENT                 136
#define IDS_DLG_PROGRAM_CONTROL_COMPANY 136
#define IDS_DLG_PROGRAM_CONTROL_DESCRIPT 137
#define IDD_LEV1_RULE                   138
#define IDS_DLG_PROGRAM_CONTROL_DUPLICATE_ITEM 138
#define IDB_BITMAP_CHECKMARK            139
#define IDS_DLG_PROGRAM_CONTROL_FULLPATH 139
#define IDD_DLG_TEXT                    140
#define IDS_COM_ERRO_COCREATE_FIALED    140
#define IDD_DLG_OPTION                  141
#define IDS_TIP_SETTING_CHANGED         141
#define IDD_DLG_TOOLS                   142
#define IDS_APP_NAME                    142
#define IDS_OUR_MAIL_URL                143
#define IDD_DLG_EYECARE                 144
#define IDS_REGISTER_DONE               144
#define IDS_REGISTER_OVERTIME           145
#define IDS_REGISTER_TRIAL_DAYS         146
#define IDD_LEV1_TIME_RULE              147
#define IDS_REGISTER_CANNOT_GETINFO     147
#define IDS_REGISTER_OVER_TIP           148
#define IDD_DIALOG1                     149
#define IDD_DLG_DNS_WHITELIST           149
#define IDS_REGISTER_WRONGSN            149
#define IDD_CHANGE_PASSWORD             150
#define IDD_POPUP_CHANGE_PASSWORD       150
#define IDS_REGISTER_RIGHT              150
#define IDD_DLG_CHKPASSWORD             151
#define IDD_POPDLG_CHKPASSWORD          151
#define IDS_PWD_NOT_SAME_WITH_CONFIRM   151
#define IDD_TOOLS                       152
#define IDS_PWD_NEW_PWD_TOO_SHORT       152
#define IDD_LEV1_TOOLS                  153
#define IDS_PWD_CHECK_FAILED            153
#define IDD_TEMPLATE                    154
#define IDS_UNKNOW_ERROR                154
#define IDD_DLG_SCREEN_SAVER            155
#define IDD_DLG_SCREENSHOT              155
#define IDS_PWD_FAILED_ON_CHANGE        155
#define IDD_DLG_WEB_HISTORY             156
#define IDS_PWD_SET_SUCCESS             156
#define IDB_BMP_ACCESSABLE              157
#define IDB_BITMAP3                     158
#define IDB_BMP_BLOCK                   158
#define IDS_DLG_PROGRAM_PATH_IN_LIMITDIR 158
#define IDB_BITMAP1                     159
#define IDB_GUI_DOCKBAR                 160
#define IDB_GUI_DOCKBAROFFICE           161
#define IDB_GUI_MDIICONS                162
#define IDI_GUI_ARROWDOWN               163
#define IDI_ICON2                       164
#define IDI_GUI_ARROWRIGHT              164
#define IDD_DLG_IMAGEBROWSER            165
#define IDD_POPDLG_IMAGEBROWSER         165
#define IDD_RIGHTREGIONDLG              166
#define IDD_DLG_WEBSITES                167
#define IDD_POPDLG_WEBSITES             167
#define IDB_HDRDOWN                     168
#define IDB_HDRUP                       169
#define IDD_DLG_SEACHWORD_LIST          170
#define IDD_DLG_SEACHWORD_HISTORY       170
#define IDD_POPDLG_SEACHWORD_HISTORY    170
#define IDD_DLG_PROGRAM                 172
#define IDI_DEFAULT                     173
#define IDI_TREE_SEACH                  176
#define IDI_TREE_OPTION                 177
#define IDI_TREE_RECORD                 178
#define IDI_TREE_HISTORY                179
#define IDI_TREE_WHITE_DNS              181
#define IDI_TREE_SCREENSHOT             183
#define IDI_TREE_DISCONNECT             184
#define IDI_TREE_EYECARE                186
#define IDI_TREE_TOOLS                  188
#define IDI_MODEL_PROTECTED             189
#define IDI_MODEL_PARENT                190
#define IDB_BITMAP2                     191
#define IDB_BITMAP4                     192
#define IDD_DIALOG2                     193
#define IDD_DLG_MIN_MAINUI              193
#define IDD_POPDLG_MIN_MAINUI           193
#define IDB_TRAY_KEY                    194
#define IDB_TRAY_LOCK                   196
#define IDB_TRAY_OPTION                 197
#define IDB_TRAY_DESKTOPIMAGE           198
#define IDI_LOCK                        199
#define IDI_KEY                         200
#define IDB_TRAY_HISTORY_WEBSITE        202
#define IDB_TRAY_HISTORY_SEARCH         203
#define IDD_POPLDG_REGISTER             204
#define IDB_BMP_LOGO                    207
#define IDB_BMP_SMALL_LOGO              208
#define IDI_ICO_SMALL_LOGO              212
#define IDI_TREE_INFO                   213
#define IDD_POP_TIPREG                  217
#define IDD_POP_REGTIP                  217
#define IDD_POP_TRAYENDTIP              218
#define IDD_POPUP_SETPWDFIRST           219
#define IDB_TOP_PART                    220
#define IDI_TEXT_LEFT                   221
#define IDI_TREE_HOME                   222
#define IDI_ICON1                       224
#define IDI_TREE_WEB                    224
#define IDI_TREE_APPCONTROL             225
#define IDI_TREE_ONLINETIME             226
#define IDI_TREE_EYECARE_BIG            227
#define IDI_TREE_BLACK_DNS              228
#define IDD_DLG_RIGHTREGION             230
#define IDC_TREE_NAVIG                  1000
#define IDS_TREE_ROOT                   1001
#define IDS_TREE_DNS_RULE               1002
#define IDC_CHK_JPEG                    1003
#define IDS_TREE_IMAGE_RULE             1003
#define IDC_BUTTON1                     1004
#define IDC_CHK_BMP                     1004
#define IDS_TREE_SEARCH_RULE            1004
#define IDC_BUTTON2                     1005
#define IDC_STALIST                     1005
#define IDC_CHK_GIF                     1005
#define IDS_TREE_CONTENT_RULE           1005
#define IDC_CANCEL                      1005
#define IDC_BTN_RESET                   1005
#define IDC_BTN_HISTORY                 1005
#define IDC_VIEW_HISTORY                1005
#define IDC_BTN_HISTORY_PAGES           1005
#define IDC_REGISTER                    1005
#define IDC_APPLY                       1006
#define IDC_LIST1                       1006
#define IDC_CHK_PNG                     1006
#define IDS_TREE_ONLINE_HOUR            1006
#define IDC_BTN_EXPORT_WEBSITES         1006
#define IDC_BTN_HISTORY_IMAGE           1006
#define IDC_BUTTON3                     1007
#define IDS_TREE_HELP                   1007
#define IDC_BTN_HISTORY_SEACHWORD       1007
#define IDC_BTN_ADD                     1007
#define IDC_BUTTON4                     1008
#define IDC_CHK_IMAGE                   1008
#define IDS_TREE_ABOUT                  1008
#define IDC_BTN_SET                     1008
#define IDC_CHK_SHOWIMAGE               1009
#define IDS_DNS_BLACK_LIST              1009
#define IDC_BTN_DEL                     1009
#define IDS_DNS_WHITE_LIST              1010
#define IDC_RIGHT_TITLE                 1014
#define IDC_COMMENT                     1016
#define IDC_LIST2                       1018
#define IDC_DNS_LIST                    1019
#define IDC_SEARCH_LIST                 1020
#define IDC_STA_IMAGETYPE               1021
#define IDC_STA_IMAGE_CHECK             1022
#define IDC_STA_IMAGESIZE               1023
#define IDC_STA_COMMENT                 1024
#define IDC_CHECK1                      1025
#define IDC_CHK_TIMECTRL                1025
#define IDC_CHK_WHITE_DNSLIST           1025
#define IDC_CHECK2                      1026
#define IDC_STA_SYSTEM                  1027
#define IDC_CHECK3                      1027
#define IDC_STA_OTHERS                  1028
#define IDC_CHK_ALL_IMAGE               1028
#define IDC_CHK_AUTOLOAD                1029
#define IDC_CHECK4                      1029
#define IDC_CHK_SEARCH_KEYWORD          1029
#define IDC_STA_CELLS                   1030
#define IDC_STA_OTHERS2                 1030
#define IDC_STA_HOTKEY                  1030
#define IDC_CHK_ALLWEBSITES             1030
#define IDC_OK                          1031
#define IDC_MAIN_OK                     1031
#define IDC_CHK_ALWAYSSHOW              1031
#define IDC_OK2                         1032
#define IDC_HOTKEY1                     1033
#define IDC_HOTKEY_SHOWDLG              1033
#define IDC_MAIN_CANCEL                 1033
#define IDC_HOTKEY2                     1034
#define IDC_CHK_ENABLE_DNS              1034
#define IDC_HOTKEY_SWITCHUSR            1034
#define IDC_CHK_ENABLE_SEARCH           1035
#define IDC_HOTKEY_LAUNCH               1035
#define IDC_STA_WHIE_DNSLIST            1039
#define IDC_STA_FRAME                   1040
#define IDC_SPIN1                       1042
#define IDC_SPIN2                       1043
#define IDC_STA_EYECARE_TIME            1046
#define IDC_EDIT_PWD                    1048
#define IDC_EDT_PWD_RETRY               1049
#define IDC_BTN_SETPWD                  1050
#define IDC_CHK_USE_SUPWD               1051
#define IDC_EDT_ENTERTIME               1052
#define IDC_EDT_RESTTIME                1053
#define IDC_EDT_ORGIN                   1054
#define IDC_EDT_NEW                     1055
#define IDC_EDT_PASSWORD                1056
#define IDC_SLIDER1                     1057
#define IDC_SLIDER_CLEAN_TIMESPAN       1058
#define IDC_STA_PROGRAMHISTORY          1062
#define IDC_STA_WEBCONTENT              1063
#define IDC_STA_IMAGE_SAVE              1064
#define IDC_BTN_CLEAR                   1065
#define IDC_STA_TIMESPAN                1066
#define IDC_STA_AUTOCLEAR               1067
#define IDC_STA_TYPES                   1069
#define IDC_STA_HISTORY                 1070
#define IDC_STA_TOOLS                   1071
#define IDC_BUN_CLEAR_CACHE             1072
#define IDC_CHK_PRON_IMAGE              1073
#define IDC_CHK_PORN_PAGE               1074
#define IDC_CHK_PORN_WEBSITES           1075
#define IDC_CHK_ALLPAGES                1076
#define IDC_SLIDER_AUTOCLEAR_TIME       1077
#define IDC_SLIDER_SAVE_TIMESPAN        1078
#define IDC_CHK_AUTOCLEAN               1079
#define IDC_CHK_SCREENSAVE              1080
#define IDC_CHK_DENY_OTHERS             1082
#define IDC_RAD_ENTER_SU_MODE           1084
#define IDC_RAD_JUST_RESET_TIMER        1085
#define IDC_STA_AFTEREYECARE_TERMINATE  1086
#define IDC_MAIN_APPLY                  1087
#define IDC_CHK_GOOGLE                  1088
#define IDC_CHK_YAHOO                   1089
#define IDC_CHK_BAIDU                   1090
#define IDC_STA_CURRENT_STATE           1091
#define IDC_STA_TIME_LEFT               1092
#define IDC_STA_SCREENSAVE_TIMESPAN     1094
#define IDC_STA_SCREENSAVE_AUTOCLEN     1095
#define IDC_STA_WEBHISTORY_AUTOCLEAN    1096
#define IDC_STA_ABOUT                   1097
#define IDC_SLIDER_IMAGECHECK_DEGREE    1098
#define IDC_CHK_ENABLE_TIMEOUT_SWITCH   1101
#define IDC_STA_TIMEOUT                 1102
#define IDC_SLD_TIMEOUT                 1103
#define IDC_CHK_ENABLE_EYECARE          1104
#define IDC_EDIT_SCOPE_MIN              1107
#define IDC_EDIT6                       1108
#define IDC_EDIT_SCOPE_MAX              1108
#define IDC_SPIN_MAX                    1109
#define IDC_SPIN_MIN                    1110
#define IDC_CHK_ENABLE_SIZE_CHECK       1111
#define IDC_IMAGES_POS                  1112
#define IDC_LIST_SEARCH_WORD            1113
#define IDC_LIST_PROGRAM                1114
#define IDC_CHK_ENABLE_APPCONTROL       1115
#define IDC_CHK_DONT_ASKME_AGAIN        1116
#define IDC_CHK_SWITCHCHILDREN_WHEN_CLOSE 1117
#define IDC_CHK_ASKME_AGAIN             1118
#define IDC_CHK_ASKME_AGAIN_WHENCLOSE   1118
#define IDC_STA_REGISTER_INFO           1118
#define IDC_WEBSITE_URL                 1119
#define IDC_OUR_EMAIL                   1120
#define IDC_OUR_MAILLIST                1121
#define ID_BTN_BESN                     1123
#define ID_BTN_BUYNOW                   1124
#define IDC_ICON_POS                    1127
#define IDC_PAGE_ICON_POS               1127
#define IDC_RADIO1                      1129
#define IDC_PAGE_TITLE                  1130
#define IDC_POS_SUBPAGE                 1131
#define IDC_EDIT1                       4011
#define IDC_EDIT_REGSN                  4011
#define IDC_EDIT2                       4012
#define IDC_EDT_RETRY                   4013
#define IDC_WND_HELLO                   5000
#define IDC_CELL_BEGIN                  5500
#define IDC_POSITION_LEFT               8001
#define IDC_POSITION_RIGHT              8002
#define IDC_MENU_SYSTRAY                32000
#define IDC_MENU_TRAY                   32000
#define IDC_MENU_TRAY_PARENT            32000
#define ID_Menu                         32771
#define ID_MAIN                         32772
#define ID_MAIN_WEBSITES                32774
#define ID_WEBSITES_WWW                 32777
#define ID__HELLO                       32778
#define ID__HELLO2                      32779
#define ID_POPUP_A1                     32781
#define ID_POPUP_A2                     32782
#define ID_TRAYMENU_MAINUI              32784
#define ID_Menu32785                    32785
#define ID__FFFFFFFFFFFFFFFFFFFFFFFFFFF 32786
#define ID__WEBSITES                    32787
#define ID_WEBSITES_WWW32788            32788
#define ID_MAIN_TOOLS                   32791
#define ID_TRAYMENU_WEBHISTORY          32799
#define ID_TRAYMENU_DESKTOPIMAGE        32800
#define ID_TRAYMENU_LOCKCOMPUTER        32801
#define ID_TRAYMENU_MODEL_PARENTS       32804
#define ID_TRAYMENU_MODEL_CHILDREN      32805
#define ID_TRAYMENU_EXIT                32806
#define ID_MAIN_REGISTER                32808
#define ID_TRAYMENU_CHANGEPASSWORD      32809
#define ID_WEBHISTORY_WEBSITES          32810
#define ID_WEBHISTORY_SEARCHKEYWORD     32811
#define ID_WEBHISTORY_IMAGES            32812

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        231
#define _APS_NEXT_COMMAND_VALUE         32813
#define _APS_NEXT_CONTROL_VALUE         1133
#define _APS_NEXT_SYMED_VALUE           167
#endif
#endif
