#ifndef _TEST_FILTER_SETTING_IACCESSNETWORKTEST_H__
#define _TEST_FILTER_SETTING_IACCESSNETWORKTEST_H__

// IAccessNetworkTest
void TestSetAndGetBlockTime();
void TestTwoModel();

#endif  // _TEST_FILTER_SETTING_IACCESSNETWORKTEST_H__