#ifndef _TEST_FILETERSETTING_IMAGECHECKTEST_H__
#define _TEST_FILETERSETTING_IMAGECHECKTEST_H__


// ImageCheckTest
void TestImageCheck();


#endif  // _TEST_FILETERSETTING_IMAGECHECKTEST_H__
