//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MainUI.rc
//
#define IDM_ABOUTBOX                    0x0010
#define IDD_ABOUTBOX                    100
#define IDS_ABOUTBOX                    101
#define IDC_TRAY_MENU                   101
#define IDC_STA_PASSWORD                101
#define IDD_MAINUI_DIALOG               102
#define IDS_TREE_LEV1_RULES             102
#define IDS_COMMENT_DNS                 103
#define IDS_COMMENT_IMAGE               104
#define IDS_COMMENT_TEXT                105
#define IDS_TREE_OPTIONS                106
#define IDS_TREE_EYECARE                107
#define IDS_TRAYMENU_SHOWUI             108
#define IDS_TRAYMENU_HIDEUI             109
#define IDR_HTML_DLGWHITEDNSLIST        110
#define IDR_HTML_DLGCHANGEPASSWORD      111
#define IDR_MAINFRAME                   128
#define IDD_DLG_HELP                    129
#define IDD_DLG_ABOUT                   130
#define IDD_DLG_IMAGERULES              132
#define IDD_DLG_ONLINE_RULE             133
#define IDD_DLG_DNS_RULE                134
#define IDD_DLG_SEARCH_RULE             135
#define IDD_DLG_CONTENT                 136
#define IDD_DLG_BLACKWORD               137
#define IDD_LEV1_RULE                   138
#define IDB_BITMAP_CHECKMARK            139
#define IDD_DLG_TEXT                    140
#define IDD_DLG_OPTION                  141
#define IDD_DLG_TOOLS                   142
#define IDD_DLG_EYECARE                 144
#define IDD_LEV1_TIME_RULE              147
#define IDD_DIALOG1                     149
#define IDD_DLG_DNS_WHITELIST           149
#define IDD_CHANGE_PASSWORD             150
#define IDD_DLG_CHKPASSWORD             151
#define IDC_TREE_NAVIG                  1000
#define IDS_TREE_ROOT                   1001
#define IDS_TREE_DNS_RULE               1002
#define IDC_CHK_JPEG                    1003
#define IDS_TREE_IMAGE_RULE             1003
#define IDC_BUTTON1                     1004
#define IDC_CHK_BMP                     1004
#define IDS_TREE_SEARCH_RULE            1004
#define IDC_BUTTON2                     1005
#define IDC_STALIST                     1005
#define IDC_CHK_GIF                     1005
#define IDS_TREE_CONTENT_RULE           1005
#define IDC_CANCEL                      1005
#define IDC_BTN_RESET                   1005
#define IDC_APPLY                       1006
#define IDC_LIST1                       1006
#define IDC_CHK_PNG                     1006
#define IDS_TREE_ONLINE_HOUR            1006
#define IDC_BUTTON3                     1007
#define IDS_TREE_HELP                   1007
#define IDC_BUTTON4                     1008
#define IDC_CHK_IMAGE                   1008
#define IDS_TREE_ABOUT                  1008
#define IDC_CHK_SHOWIMAGE               1009
#define IDS_DNS_BLACK_LIST              1009
#define IDS_DNS_WHITE_LIST              1010
#define IDC_RIGHT_TITLE                 1014
#define IDC_COMMENT                     1016
#define IDC_LIST2                       1018
#define IDC_DNS_LIST                    1019
#define IDC_SEARCH_LIST                 1020
#define IDC_STA_IMAGETYPE               1021
#define IDC_STA_IMAGE_CHECK             1022
#define IDC_STA_IMAGESIZE               1023
#define IDC_STA_COMMENT                 1024
#define IDC_CHECK1                      1025
#define IDC_CHK_TIMECTRL                1025
#define IDC_CHK_WHITE_DNSLIST           1025
#define IDC_CHECK2                      1026
#define IDC_STA_SYSTEM                  1027
#define IDC_STA_OTHERS                  1028
#define IDC_CHK_AUTOLOAD                1029
#define IDC_STA_CELLS                   1030
#define IDC_STA_OTHERS2                 1030
#define IDC_STA_HOTKEY                  1030
#define IDC_OK                          1031
#define IDC_HOTKEY1                     1033
#define IDC_HOTKEY2                     1034
#define IDC_CHK_ENABLE_DNS              1034
#define IDC_CHK_ENABLE_SEARCH           1035
#define IDC_STA_WHIE_DNSLIST            1039
#define IDC_STA_FRAME                   1040
#define IDC_SPIN1                       1042
#define IDC_SPIN2                       1043
#define IDC_STA_EYECARE_TIME            1046
#define IDC_EDIT_PWD                    1048
#define IDC_EDT_PWD_RETRY               1049
#define IDC_BTN_SETPWD                  1050
#define IDC_CHK_USE_SUPWD               1051
#define IDC_EDT_ENTERTIME               1052
#define IDC_EDT_RESTTIME                1053
#define IDC_EDT_ORGIN                   1054
#define IDC_EDT_NEW                     1055
#define IDC_EDT_PASSWORD                1056
#define IDC_EDIT1                       4011
#define IDC_EDIT2                       4012
#define IDC_EDT_RETRY                   4013
#define IDC_WND_HELLO                   5000
#define IDC_CELL_BEGIN                  5500
#define IDC_POSITION_LEFT               8001
#define IDC_POSITION_RIGHT              8002
#define IDC_MENU_SYSTRAY                32000
#define IDC_MENU_TRAY                   32000
#define ID_Menu                         32771
#define ID_MAIN                         32772
#define ID_MAIN_WEBSITES                32774
#define ID_MAIN_EXIT                    32775
#define ID_WEBSITES_WWW                 32777
#define ID__HELLO                       32778
#define ID__HELLO2                      32779
#define ID_POPUP_A1                     32781
#define ID_POPUP_A2                     32782
#define ID_TRAYMENU_MAINUI              32784
#define ID_Menu32785                    32785
#define ID__FFFFFFFFFFFFFFFFFFFFFFFFFFF 32786
#define ID__WEBSITES                    32787
#define ID_WEBSITES_WWW32788            32788
#define ID_MAIN_TOOLS                   32791
#define ID_TOOLS_WEBHISTORY             32792
#define ID_TOOLS_DESKTOPIMAGE           32793
#define ID_MAIN_CHILDREN                32794
#define ID_MAIN_CHANGEPASSWORD          32795
#define ID_MAIN_PARENTS                 32797

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        152
#define _APS_NEXT_COMMAND_VALUE         32798
#define _APS_NEXT_CONTROL_VALUE         1057
#define _APS_NEXT_SYMED_VALUE           112
#endif
#endif
