#ifndef _INCLUDE_COM_ACTION_CODE_DEFINE_H__
#define _INCLUDE_COM_ACTION_CODE_DEFINE_H__

#define ACTION_IMAGE_CHECK_PASS 0
#define ACTION_IMAGE_CHECK_DENY 1
#define ACTION_IMAGE_CHECK_ENABLE 2

#endif  //_INCLUDE_COM_ACTION_CODE_DEFINE_H__