// FilterSetting.idl : FilterSetting 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(FilterSetting.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(5C1696AA-6E3E-4B97-8B0C-FEF2A21FF50F),
	dual,
	nonextensible,
	helpstring("IGlobalChecker 接口"),
	pointer_default(unique)
]
interface IGlobalChecker : IDispatch{
	[id(1), helpstring("method addBlackDNS")] HRESULT addBlackDNS([in] BSTR dns);
	[id(2), helpstring("method addWhiteDNS")] HRESULT addWhiteDNS([in] BSTR dns);
	[id(3), helpstring("method enableDNSCheck")] HRESULT enableDNSCheck([in] VARIANT_BOOL enable);
	[id(4), helpstring("method removeBlackDNS")] HRESULT removeBlackDNS(BSTR blackDNS);
	[id(5), helpstring("method removeWhiteDNS")] HRESULT removeWhiteDNS(BSTR whiteDNS);
};
[
	uuid(5B1BA4DF-89BC-4E1C-8C3D-A75EA1233764),
	version(1.0),
	helpstring("FilterSetting 1.0 类型库")
]
library FilterSettingLib
{
	importlib("stdole2.tlb");
	[
		uuid(406FA387-8E48-4A60-B13B-30B7EB9E32F3),
		helpstring("GlobalChecker Class")
	]
	coclass GlobalChecker
	{
		[default] interface IGlobalChecker;
	};
};
