#ifndef _TEST_SOFTWARE_ENCRYPT_BASEENCRYPTTEST_H__
#define _TEST_SOFTWARE_ENCRYPT_BASEENCRYPTTEST_H__

#include "stdafx.h"



void TestBaseEncry();

#endif  // _TEST_SOFTWARE_ENCRYPT_BASEENCRYPTTEST_H__